services:
  serpa-maps:
    image: ghcr.io/simonwehle/serpa-maps:latest
    container_name: serpa-maps
    restart: unless-stopped
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    ports:
      - "53164:53164"
    env_file:
      - .env
    volumes:
      - serpa-assets:/app/uploads
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:bookworm
    container_name: serpa-maps-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pg-data:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: serpa-maps-martin
    restart: unless-stopped
    ports:
      - "7135:3000"
    volumes:
      - ./sprites:/sprites:ro
      - ./styles:/styles:ro
      - ./fonts:/fonts:ro
      - ./config.yaml:/config.yaml:ro
      - ./tiles:/tiles:ro
    command: --config /config.yaml

volumes:
  pg-data:
  serpa-assets:
